config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tennis_courts do
    resources :reviews, only: [:new, :create]
    resources :schedules, only: [:new, :edit, :create, :update]
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:update] do
    resources :chatrooms, only: [:create]
    resources :orders, only: [:create]
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end

  resources :reviews, only: :destroy
  get 'dashboard', to: 'pages#dashboard'
  resources :orders, only: [:show] do
  resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/tennis_court.rb
class TennisCourt < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
  has_many :schedules
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  include PgSearch::Model
  pg_search_scope :search_by_court_name_and_address,
    against: [ :court_name, :address, :description, :surface_type ],
    using: {
      tsearch: { prefix: true }
    }
  validates :court_name, presence: true
  validates :address, presence: true
  validates :price_per_hour, presence: true
  validates :surface_type, presence: true

  def total_booked_hours
    total = 0
    bookings.where(status: "accepted").where("beginning_date_time < ? ", DateTime.now).each do |booking|
      booking_total = ((booking.end_date_time - booking.beginning_date_time) / (60 * 60)).to_i
      p booking_total
      total += booking_total
    end
    return total
  end

  monetize :price_cents
end

app/controllers/tennis_courts_controller.rb
class TennisCourtsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @tennis_court = TennisCourt.new
    @tennis_courts = TennisCourt.all
    if params[:query].present?
      @tennis_courts = TennisCourt.search_by_court_name_and_address(params[:query])
    else
      @tennis_courts = TennisCourt.all
    end
    @markers = @tennis_courts.geocoded.map do |tennis_court|
      {
        lat: tennis_court.latitude,
        lng: tennis_court.longitude,
        info_window: render_to_string(partial: "info_window", locals: { tennis_court: tennis_court })
      }
    end
  end

  def show
    @tennis_court = TennisCourt.find(params[:id])
    @review = Review.new
    @booking = Booking.new
    @schedule = Schedule.new
    @current_registration = @tennis_court.bookings.find_by(user: current_user)

     @markers = [
      {
        lat: @tennis_court.latitude,
        lng: @tennis_court.longitude,
        info_window: render_to_string(partial: "info_window", locals: { tennis_court: @tennis_court })
      }
    ]
  end

  def new
    @tennis_court = TennisCourt.new
  end

  def create
    @tennis_court = TennisCourt.new(tennis_court_params)
    @tennis_court.user = current_user
    if @tennis_court.save!
      redirect_to tennis_courts_path(@tennis_court)
    else
      render :new
    end
  end

  def destroy
    @tennis_court = TennisCourt.find(params[:id])
    @tennis_court.destroy
    redirect_to tennis_courts_path
  end

  def edit
    @tennis_court = TennisCourt.find(params[:id])
  end

  def update
    @tennis_court = TennisCourt.find(params[:id])
    @tennis_court.update(tennis_court_params)
    redirect_to tennis_court_path(@tennis_court)
  end

  private

  def tennis_court_params
    params.require(:tennis_court).permit(:court_name, :address, :price_per_hour, :description, :surface_type, :photo)
  end
end

app/views/tennis_courts/_info_window.html.erb
<%= link_to tennis_court_path(tennis_court) do %>
  <div class="window-map">
    <div class="window-map-photo">
      <% if tennis_court.photo.attached? %>
        <%= cl_image_tag tennis_court.photo.key, crop: :fill %>
      <% else %>
        <%= image_tag "no-photo-available-icon-8.jpg" %>
      <% end %>
    </div>
    <div class="window-map-info">
      <h2><i class="fas fa-baseball-ball"></i></i></i>    <%= tennis_court.court_name %></h2>
      <p><i class="fas fa-user-alt"></i> <%= tennis_court.user.first_name %></p>
      <p><i class="fas fa-map-marker-alt"></i> <%= tennis_court.address %></p>
      <p><i class="fas fa-euro-sign"></i> <%= tennis_court.price_per_hour %></p>
    </div>
  </div>
<% end %>

app/views/tennis_courts/edit.html.erb
<div class="container py-5">
  <div class="bg-white rounded p-3 shadow">
    <h3>Edit your Tennis Court</h3>
      <%= simple_form_for(@tennis_court) do |f| %>
        <%= f.input :court_name %>
        <%= f.input :address %>
        <%= f.input :price_per_hour %>
        <%= f.input :surface_type, collection: [ "Clay", "Grass", "Hard", "Other"] %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
  </div>
</div>

app/views/tennis_courts/index.html.erb
<div class="main-container">
    <div class="d-flex justify-content-between ml-3">
      <%= form_tag tennis_courts_path, method: :get, class: "d-flex m-3" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a Tennis court"
        %>
        <%= submit_tag "Search", class: "btn btn-warning ml-1" %>
      <% end %>
    </div>
  <div class="row">
    <div class="col-md-12 col-lg-6" id="cards-container">
      <% @tennis_courts.each do |tennis_court| %>
        <%= link_to tennis_court_path(tennis_court), class: "card-links" do %>
          <div class="card-product">
            <div class="card-product-photo">
                <% if tennis_court.photo.attached? %>
                  <%= cl_image_tag tennis_court.photo.key, crop: :fill %>
                <% else %>
                  <%= image_tag "no-photo-available-icon-8.jpg" %>
                <% end %>
            </div>
            <div class="card-product-infos">
              <h1 class="card-title"> <%= tennis_court.court_name %></h1>
              <p><%= tennis_court.address %></p>
              <p> <strong><%= "#{tennis_court.price_per_hour}€" %></strong> </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-12 col-lg-6">
      <div id="map" class="position-sticky"
           style="height: 900px; width: 100%;"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/tennis_courts/new.html.erb
<div class="container py-5">
      <div class="bg-white rounded p-3 shadow">
        <h3>Your Tennis Court</h3>
        <%= simple_form_for(@tennis_court) do |f| %>
        <%= f.input :court_name %>
        <%= f.input :address, id: "tennis_court_address" %>
        <%= f.input :price_per_hour %>
        <%= f.input :surface_type, collection: [ "Clay", "Grass", "Hard", "Other"] %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Create court", class: "btn btn-warning"%>
        <% end %>
  </div>
</div>

app/views/tennis_courts/show.html.erb
 <% content_for :meta_title, "#{@tennis_court.court_name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @tennis_court.description %>

  <div class="d-flex justify-content-center">
    <% if @tennis_court.photo.attached? %>
    <div class="image-container" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @tennis_court.photo.key, height: 300, width: 400, crop: :fill %>')">
     <div class="text">
       <h1><%= @tennis_court.court_name %></h1>
     </div>
   </div>
   <% else %>
   <%= image_tag "no-photo-available-icon-8.jpg" %>
   <% end %>
   <br>
 </div>

<div class="container mt-4">
  <div class="row search">
    <div class="d-flex align-items-center">
      <% if @tennis_court.user != current_user && @current_registration != nil%>
      <div>
        <span class="badge <%= @current_registration.badge_status %>"><%= @current_registration.status %></span>

      </div>
      <nav class="navbar navbar-light">
        <%= simple_form_for([@tennis_court, @booking], html:{ class:"form-inline" }) do |f| %>
        <%= f.input :beginning_date_time, label: "From", as: :string%>
        <%= f.input :end_date_time, label: "Untill", as: :string%>
        <%= f.submit "Book now", class: "btn btn-warning ml-1" %>
        <% end %>
      </nav>
      <% elsif @tennis_court.user == current_user %>
      <% @tennis_court.bookings.each do |booking| %>
      <%= booking.user.email  %>
      <%= simple_form_for booking, method: :patch do |f| %>
      <%= f.input :status, collection: ["accepted", "rejected"] %>
      <%= f.submit class: "btn btn-warning"%>
      <% end %>
      <% end %>
      <% else %>

      <nav class="navbar navbar-light">
        <%= simple_form_for([@tennis_court, @booking], html:{ class:"form-inline" }) do |f| %>
        <%= f.input :beginning_date_time, label: "From", as: :string, input_html: {type: :date, class: "m-2"}%>
        <%= f.input :end_date_time, label: "Untill", as: :string, input_html: {type: :date, class: "ml-2"} %>
        <%= f.submit "Book now", class: "btn btn-warning ml-1" %>
        <% end %>
      </nav>
      <% end %>
    </div>
  </div>

<div class="row pb-3 mt-4">
  <div class="col-6">
    <h5><%= @tennis_court.description %></h5>
    <p><%= @tennis_court.surface_type %></p>
    <p><%= "#{@tennis_court.price_per_hour}€" %></p>
    <% if @tennis_court.user == current_user %>
    <small><%= link_to 'Edit', edit_tennis_court_path(@tennis_court) %></small>
    <small><%= link_to 'Delete', tennis_court_path(@tennis_court), method: :delete, data: { confirm: 'Are you sure?' } %></small>
    <% end %>
 <p class="mt-3"><%= link_to "Back to tennis courts", tennis_courts_path %></p>
  </div>
   <div id="map"
   style="height: 300px; width: 49%;"
   data-markers="<%= @markers.to_json %>"
   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>
<div class="row pt-3 border-top">
  <div class="col-12 col-sm-6">
    <h3>Reviews</h3>
    <% if @tennis_court.reviews.empty? %>
    <small><em class="text-muted">Be the first one to review this list</em></small>
    <% end %>
    <% @tennis_court.reviews.each do |review| %>
    <div>
      <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
      <p class="mb-0"><%= review.user.first_name %></p>
      <p class="mb-0"><%= review.content %></p>
      <p class="mb-0"><%= "🎾" * review.rating %></p>
    </div>
    <hr>
    <% end %>
  </div>
  <div class="col-12 col-sm-6">
    <div class="bg-white rounded p-3 mb-5">
      <h5>Add your review</h5>
      <%= simple_form_for [@tennis_court, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", id:"review_rating" %>
      <%= f.submit "Send your review", class:"btn-secondary"%>
      <% end %>
      </div>
    </div>
  </div>
</div>