config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tennis_courts do
    resources :reviews, only: [:new, :create]
    resources :schedules, only: [:new, :edit, :create, :update]
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:update] do
    resources :chatrooms, only: [:create]
    resources :orders, only: [:create]
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end

  resources :reviews, only: :destroy
  get 'dashboard', to: 'pages#dashboard'
  resources :orders, only: [:show] do
  resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/pages/dashboard.html.erb
<div class="main-container">

  <h1>Hello <%= current_user.first_name%></h1>
  <div class="row">

    <div class="col-md-12 col-lg-6">
      <div class="dashboard-stat">
        <% @mybookings.each do |mybooking| %>
        <% if mybooking.beginning_date_time >= Time.now %>
          <h2> Next booking</h2>
            <div class="card-product">
              <%= link_to tennis_court_path(mybooking.tennis_court) do %>
              <div class="card-product-photo">
                <% if mybooking.tennis_court.photo.attached? %>
                  <%= cl_image_tag mybooking.tennis_court.photo.key, crop: :fill %>
                <% else %>
                  <%= image_tag "no-photo-available-icon-8.jpg" %>
                <% end %>
                </div>
              <div class="card-product-infos">
                <h1>Reservation for <%= mybooking.tennis_court.court_name %></h1>
                <p>Status: <strong><%= mybooking.status %></strong></p>
                <p><strong><%= mybooking.beginning_date_time.strftime("%b %e from %l:%M%p")%></strong>
                  <strong><%= mybooking.end_date_time.strftime("to %l:%M%p") %></strong></p>
                <%= link_to 'chat-room', chatroom_path(mybooking.chatrooms.first) %>
              </div>
              <div>
                <%= form_tag  booking_orders_path(mybooking) do %>
                <%= hidden_field_tag 'booking_id', mybooking.id %>
                <%= submit_tag 'Purchase', class: 'btn btn-warning mr-4' %>
                <% end %>
              </div>
              <% end %>
            </div>

        <% else %>
          <h2>Past booking </h2>
              <div class="card-product">
                <% if mybooking.tennis_court.photo.attached? %>
                  <%= cl_image_tag mybooking.tennis_court.photo.key, crop: :fill %>
                <% else %>
                  <%= image_tag "no-photo-available-icon-8.jpg" %>
                <% end %>
                <div class="card-product-infos">
                  <h1>Reservation for <%= mybooking.tennis_court.court_name %></h1>
                  <p>Status: <strong><%= mybooking.status %></strong></p>
                  <p><strong><%= mybooking.beginning_date_time.strftime("%b %e from %l:%M%p")%></strong>
                    <strong><%= mybooking.end_date_time.strftime("to %l:%M%p") %></strong></p>
                  <%= link_to 'chat-room', chatroom_path(mybooking.chatrooms.first) %>
                </div>

              </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-md-12 col-lg-6">
        <% if current_user.tennis_courts.present? %>

          <div class="dashboard-stat">
            <h1><%= current_user.first_name %> stat as a Host </h1>
            <% @tennis_courts.each do |tennis_court| %>
              <div>
                <h2>How much money you made as a host</h2>
                <p><%= tennis_court.court_name%>: <%= tennis_court.total_booked_hours * tennis_court.price_per_hour %> € </p>
              </div>
            <% end %>
          </div>

          <div class="dashboard-stat">
            <h1><%= current_user.first_name %> Hosting Summary </h1>
            <% @tennis_courts.each do |tennis_court| %>
                <% tennis_court.bookings.order(status: :desc).each do |booking| %>
                  <div class="card-product">
                    <%= link_to tennis_court_path(tennis_court) do %>
                      <div class="card-product-photo">
                          <% if tennis_court.photo.attached? %>
                            <%= cl_image_tag tennis_court.photo.key, crop: :fill %>
                          <% else %>
                            <%= image_tag "no-photo-available-icon-8.jpg" %>
                          <% end %>
                      </div>
                      <div class="card-product-infos">
                        <h2><%= booking.tennis_court.court_name %></h2>
                        <p><strong>status: <%= booking.status %></strong></p>
                        <p>Demand from <%= booking.user.first_name %></p>
                        <p><%= booking.beginning_date_time.strftime("%b %e from %l:%M%p") %>
                          <%= booking.end_date_time.strftime("to %l:%M%p") %></p>
                        <%= link_to 'chat-room', chatroom_path(booking.chatrooms.first) %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
          </div>



          <div class="dashboard-stat">
            <h1><%= current_user.first_name %> Tennis Courts</h1>
              <% @tennis_courts.each do |tennis_court| %>
               <%= link_to tennis_court_path(tennis_court) do %>
                  <div class="card-product">
                    <div class="card-product-photo">
                        <% if tennis_court.photo.attached? %>
                          <%= cl_image_tag tennis_court.photo.key, crop: :fill %>
                        <% else %>
                          <%= image_tag "no-photo-available-icon-8.jpg" %>
                        <% end %>
                    </div>
                    <div class="card-product-infos">
                      <h1 class="card-title"> <%= tennis_court.court_name %></h1>
                      <p><%= tennis_court.address %></p>
                      <p><%= "#{tennis_court.price_per_hour}€" %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
          </div>


        <% end %>
    </div>
  </div> 
</div>
 

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dv3mbtcpg/image/upload/v1623729947/ryan-searle-qjrjJnFypa0-unsplash_pmqdxe_szkmo5.jpg);">
  <div class="container">
    <div class="toptext">
      <div class="d-flex justify-content-center">
      <nav class="navbar navbar-light">
        <div class="d-flex flex-column bd-highlight mb-3">
        <h1>Tennis courts near you</h1>
        <h2>No yearly subcriptions</h2>
        </div>
      </nav>
    </div>
    </div>
     <br>
    <br>
    <br>
    <br>
    <br>
    <br>
     <br>


    <br>
    <div class="search">
      <div class="d-flex align-items-center">
        <nav class="navbar navbar-light">
          <%= link_to "Discover all courts", tennis_courts_path, class: "btn btn-warning p-2 font-weight-bold rounded"  %>
       </nav>
     </div>
   </div>
 </div>
</div>